### ISSUE TITLE
PUTting resources failing to cause actual updates

### ISSUE THREAD

**Issue by gliese1337** [AmericanCouncils/AyamelResourceApiServer#250]
I've just transcoded a large number of subtitle files and need to automatically update all of the corresponding resources to point at the new URLs for the new format. I've got a Python script that fetches all of the resources in a big list, replaces the files array, and then PUTs the result back to update the Resource Library. I get 200 OK responses back, but none of the resources are actually updated. This is a sample of one of the resources I'm trying to PUT back:

```
{
    "status":"normal",
    "content":{"files":[{
        "mimeType":"text/x-ssa",
        "representation":"transcoding",
        "bytes":7072,
        "downloadUri":"https://s3.amazonaws.com/ayamel/53cecce833e57c72108b4569subs.ass",
        "attributes":{"kind":"subtitles"}
    }]},
    "dateAdded":"1406061800",
    "description":"",
    "title":"Consultant 2",
    "relations":[{"objectId":"53b5e35033e57c85448b4571","subjectId":"53cecce833e57c72108b4569","client":{"id":"byu_demo","name":"BYU Demos"},"attributes":[],"type":"transcript_of","id":"53cecce933e57c72108b456a"}],
    "dateModified":"1406061801",
    "languages":{"iso639_3":["ara"]},
    "client":{"id":"byu_demo","name":"BYU Demos"},
    "keywords":"subtitles",
    "type":"data",
    "id":"53cecce833e57c72108b4569",
    "clientUser":{}
}
```

and this is the corresponding response from the Resource Library:

```
{
    "resource":{
        "id":"53cecce833e57c72108b4569",
        "title":"Consultant 2",
        "description":"",
        "keywords":"subtitles",
        "languages":{"iso639_3":["ara"]},
        "type":"data",
        "date Added":"1406061800",
        "dateModified":"1439938257",
        "status":"normal",
        "clientUser":{},
        "client":{"id":"byu_demo","name":"BYU Demos"},
        "content":{"files"[{
            "downloadUri":"https:\/\/s3.amazonaws.com\/ayamel\/2d52e877211421240f964dfcb73d82e5.vtt",
            "bytes":4826,
            "representation":"original",
            "quality":1,
            "mime":"text\/vtt",
            "mimeType":"text\/vtt",
            "attributes":[]
        }]},
        "relations":[]
    },
    "response":{"code":200,"message":"OK"}
}
```

**Comment by evillemez** [comment]
@gliese1337 I think I missed the notification for this, apologies.

You can't update the entire structure at once.  To update relations, you need to use the relations API, and to update content you need to use the content routes.

It's a little unwieldy, but originally we had planned to only handle content as raw file uploads, not external references... so there's that extra step.

The top-level data in the resource should still be modifiable - if that's not actually being modified, let me know.

**Comment by gliese1337** [comment]
@evillemez OK, I'm pretty sure I'm doing things right now (top-level data is being updated correctly, by the way), but I've got a new hiccup: I'm getting 400 errors when I send my remoteFiles list to the content upload URL. Specifically:

```
{"response {"code":400,"message":"Object(Ayamel\\ResourceBundle\\Document\\FileReference).mimeType:\n    Files with mimeType [text\/x-ssa] cannot be validated."}}
```

The object being sent is of the following form:

```
{
    "remoteFiles": [{
        "downloadUri":"some-aws-url",
        "bytes":1234,
        "mimeType":"text/x-ssa",
        "representation":"transcoding",
        "attributes": {
            "kind":"subtitles"
        }
    }]
}
```

If the Resource Library doesn't recognize a certain mime type, shouldn't it just skip attribute validation?
